name: Custom issue template
description: Another question or task outside standard categories.
title: "[Custom]: "
labels:
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Use this template for non-standard questions or tasks.
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: Describe the request or issue.
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals/outcome
      description: What result do you expect?
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: References or context
      description: Add links, logs, or examples.
    validations:
      required: false
