name: Feature request
description: Propose a new feature or improvement.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Describe the desired functionality and motivation.
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem will this change solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you see this feature being implemented?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have other options been considered?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, examples, or other details.
    validations:
      required: false
