name: Potential integration candidates
description: Propose integrations or compatible components for PoR.
title: "[Integration]: "
labels:
  - integration
body:
  - type: markdown
    attributes:
      value: |
        Propose potential integrations or components that could strengthen PoR.
  - type: textarea
    id: candidate
    attributes:
      label: Integration candidate
      description: Name of the component/project/module.
      placeholder: For example, a monitoring tool, driver, or library.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this integration useful for the project?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Expected integration scope
      description: Which modules, APIs, or parts of the code will be involved?
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: Risks and constraints
      description: Potential risks or security/compatibility requirements.
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: Add documentation or relevant resources.
    validations:
      required: false
